// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	os "os"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	config "github.com/kornetvba/YandShortUrl/internal/config/config"
	repository "github.com/kornetvba/YandShortUrl/internal/repository"
)

// MockURLStorage is a mock of URLStorage interface.
type MockURLStorage struct {
	ctrl     *gomock.Controller
	recorder *MockURLStorageMockRecorder
}

// MockURLStorageMockRecorder is the mock recorder for MockURLStorage.
type MockURLStorageMockRecorder struct {
	mock *MockURLStorage
}

// NewMockURLStorage creates a new mock instance.
func NewMockURLStorage(ctrl *gomock.Controller) *MockURLStorage {
	mock := &MockURLStorage{ctrl: ctrl}
	mock.recorder = &MockURLStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStorage) EXPECT() *MockURLStorageMockRecorder {
	return m.recorder
}

// AppendRecord mocks base method.
func (m *MockURLStorage) AppendRecord(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendRecord", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendRecord indicates an expected call of AppendRecord.
func (mr *MockURLStorageMockRecorder) AppendRecord(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRecord", reflect.TypeOf((*MockURLStorage)(nil).AppendRecord), arg0, arg1)
}

// GetRecord mocks base method.
func (m *MockURLStorage) GetRecord(arg0 string) (*repository.URLRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecord", arg0)
	ret0, _ := ret[0].(*repository.URLRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecord indicates an expected call of GetRecord.
func (mr *MockURLStorageMockRecorder) GetRecord(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecord", reflect.TypeOf((*MockURLStorage)(nil).GetRecord), arg0)
}

// LoadRecords mocks base method.
func (m *MockURLStorage) LoadRecords(arg0 *config.FilePathType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadRecords", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadRecords indicates an expected call of LoadRecords.
func (mr *MockURLStorageMockRecorder) LoadRecords(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadRecords", reflect.TypeOf((*MockURLStorage)(nil).LoadRecords), arg0)
}

// ReadFile mocks base method.
func (m *MockURLStorage) ReadFile(arg0 *config.FilePathType) (*os.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", arg0)
	ret0, _ := ret[0].(*os.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockURLStorageMockRecorder) ReadFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockURLStorage)(nil).ReadFile), arg0)
}

// SaveFile mocks base method.
func (m *MockURLStorage) SaveFile(arg0 *config.FilePathType) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveFile", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveFile indicates an expected call of SaveFile.
func (mr *MockURLStorageMockRecorder) SaveFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveFile", reflect.TypeOf((*MockURLStorage)(nil).SaveFile), arg0)
}
